default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: genderquest_development

test:
  <<: *default
  database: genderquest_test
  # heroku needs this: ?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory

#production:
#  <<: *default
#  database: "production_database_name"